package view

import (
	"fmt"
	"strings"
)

// imgResponsiveWidths are the widths generated by the optimize-images pass
// for full-bleed images. Every full-bleed source is wider than the largest
// (1600px), so all four variants always exist.
var imgResponsiveWidths = []int{400, 800, 1200, 1600}

// imgVariant swaps the extension on a /static/img/foo.jpg path, e.g.
// imgVariant("/static/img/foo.jpg", ".avif") == "/static/img/foo.avif".
func imgVariant(src, ext string) string {
	if i := strings.LastIndex(src, "."); i >= 0 {
		return src[:i] + ext
	}
	return src + ext
}

// imgSrcset builds a responsive srcset string for the width variants the
// optimize-images pass produced: "<base>-400w<ext> 400w, …". An empty ext
// keeps the source's own extension (the JPG fallback srcset).
func imgSrcset(src, ext string) string {
	base, origExt := src, ""
	if i := strings.LastIndex(src, "."); i >= 0 {
		base, origExt = src[:i], src[i:]
	}
	if ext == "" {
		ext = origExt
	}
	parts := make([]string, 0, len(imgResponsiveWidths))
	for _, w := range imgResponsiveWidths {
		parts = append(parts, fmt.Sprintf("%s-%dw%s %dw", base, w, ext, w))
	}
	return strings.Join(parts, ", ")
}
